/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "АГУУЛГА",
      items: ["Tanilcuulga", "nevtreh"],
    },
    {
      type: "category",
      label: "ХАРИЛЦАГЧ БҮРТГЭХ/ ДАНС НЭЭХ",
      items: ["burtgel", "dans"],
    },
    {
      type: "category",
      label: "Гүйлгээ",
      items: ["guilgee", "guilgee2"],
    },
    {
      type: "category",
      label: "Нябо тайлан",
      items: ["nTailan1"],
    },

    {
      type: "category",
      label: "ЗЭЭЛИЙН БҮРТГЭЛ",
      items: [
        "burt_zeeldegch",

        {
          type: "category",
          label: "ЗЭЭЛИЙН ХҮСЭЛТ",
          items: ["zeeliinHuselt", "zeelSudlah", "shiidwer", "zeelGeree"],
        },
        ,
        {
          type: "category",
          label: "ЗЭЭЛИЙН ТАЙЛАН",
          items: ["zeeliinTailan", "Zotailan"],
        },
      ],
    },

    // Guilgee
    {
      type: "category",
      label: "Гүйлгээ өндөрлөх, тайлан баланс гаргах",
      items: ["guilgTuluv4", "guilgTuluv3", "nTailan3"],
    },
    {
      type: "category",
      label: "Нябо тохиргоо",
      items: ["guilgTuluv4", "guilgTuluv3", "nTailan3"],
    },

    ,
  ],
};

module.exports = sidebars;
