name: Draft branch CI/CD

on:
  push:
    branches: [draft]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ssh script
        uses: appleboy/ssh-action@master
        env:
          SSH_ROOT: ${{secrets.SSH_ROOT}}
          GIT_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          host: ${{ secrets.MASTER_BRANCH_HOST }}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          envs: SSH_ROOT,GIT_TOKEN,GIT_BRANCH
          script: |
            cd ~/efine/efine_source
            rm -rf my-website
            git clone --branch $GIT_BRANCH https://gantulgao:$GIT_TOKEN@github.com/gantulgao/my-website.git
            cd my-website
            chmod +x ./post_commit.sh
            ./post_commit.sh
            chmod -x ./post_commit.sh
